-- MySQL Script generated by MySQL Workbench
-- Wed Jan 12 20:29:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_matriculas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_matriculas` ;

-- -----------------------------------------------------
-- Schema db_matriculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_matriculas` DEFAULT CHARACTER SET utf8 ;
USE `db_matriculas` ;

-- -----------------------------------------------------
-- Table `db_matriculas`.`tbl_bootcamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_matriculas`.`tbl_bootcamp` ;

CREATE TABLE IF NOT EXISTS `db_matriculas`.`tbl_bootcamp` (
  `bootcamp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bootcamp_nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`bootcamp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_matriculas`.`tbl_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_matriculas`.`tbl_alumno` ;

CREATE TABLE IF NOT EXISTS `db_matriculas`.`tbl_alumno` (
  `alumno_id` INT(11) NOT NULL,
  `alumno_nombre` VARCHAR(255) NOT NULL,
  `alumno_email` VARCHAR(255) NULL,
  PRIMARY KEY (`alumno_id`),
  UNIQUE INDEX `alumno_email_UNIQUE` (`alumno_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_matriculas`.`tbl_matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_matriculas`.`tbl_matricula` ;

CREATE TABLE IF NOT EXISTS `db_matriculas`.`tbl_matricula` (
  `matricula_id` INT(11) NOT NULL,
  `matricula_grupo` VARCHAR(45) NOT NULL,
  `matricula_fecha_registro` DATE NULL COMMENT 'fecha de registro',
  `bootcamp_id` INT(11) NOT NULL,
  `alumno_id` INT(11) NOT NULL,
  PRIMARY KEY (`matricula_id`),
  CONSTRAINT `fk_tbl_matricula_tbl_bootcamp`
    FOREIGN KEY (`bootcamp_id`)
    REFERENCES `db_matriculas`.`tbl_bootcamp` (`bootcamp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_tbl_alumno1`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_matriculas`.`tbl_alumno` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_matriculas`.`tbl_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_matriculas`.`tbl_curso` ;

CREATE TABLE IF NOT EXISTS `db_matriculas`.`tbl_curso` (
  `curso_id` INT(11) NOT NULL,
  `curso_nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`curso_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_matriculas`.`tbl_profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_matriculas`.`tbl_profesor` ;

CREATE TABLE IF NOT EXISTS `db_matriculas`.`tbl_profesor` (
  `profesor_id` INT(11) NOT NULL,
  `profesor_nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`profesor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_matriculas`.`tbl_matricula_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_matriculas`.`tbl_matricula_curso` ;

CREATE TABLE IF NOT EXISTS `db_matriculas`.`tbl_matricula_curso` (
  `matcur_id` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT(11) NOT NULL,
  `profesor_id` INT(11) NOT NULL,
  `matricula_id` INT(11) NOT NULL,
  PRIMARY KEY (`matcur_id`),
  CONSTRAINT `fk_tbl_matricula_curso_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_matriculas`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_curso_tbl_profesor1`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `db_matriculas`.`tbl_profesor` (`profesor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_curso_tbl_matricula1`
    FOREIGN KEY (`matricula_id`)
    REFERENCES `db_matriculas`.`tbl_matricula` (`matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
